services:
  desktop:
    container_name: desktop
    image: ghcr.io/amitie10g/kali-rolling:latest
    restart: always
    cap_add:
      - NET_ADMIN
      - NET_RAW
    ports:
      - 13389:3389
    volumes:
      - ./kali/kali:/home/kali
      - ./kali/root:/root

  vulnerable-webapps:
    container_name: vulnerable
    image: ghcr.io/amitie10g/kali-rolling:labs
    restart: always
    ports:
      - 42000:42000
      - 42001:42001
