name: ngrok-ssh
on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: tmshkr/ngrok-ssh@latest
        with:
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
          NGROK_CONFIG_FILE: "ngrok.yml"
      - run: npm start
